version: '3'

services:

  python:
    build: 
      context: .
    environment: 
      - TELEGRAM_BOT_TOKEN=xxx
      - TELEGRAM_ADMIN_ID=xxx
    volumes:
      - ./src:/src
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    